### ISSUE TITLE
Installation prerequisite

### ISSUE THREAD

**Issue by Rombur** [AMDResearch/DAGEE#1]
I am a little bit confused on what packages are necessary to use the library and which ones are necessary to compile the examples. The prerequisite says that I need `atmi comgr hcc hip-base hip-hcc hsa-ext-rocr-dev hsa-rocr-dev hsakmt-roct hsakmt-roct-dev rocm-cmake rocm-dev rocm-device-libs` but later on in the documentation only need `atmi` seems to be required. I am using a cluster where `hsakmt-roct` is not installed does this mean that I cannot use DAGEE at all or I just cannot compile the examples? `atmi` has been installed using the package manager so I assume that I can use it and that I don't need to build my own version of `atmi`.

**Comment by amberhassaan** [comment]
Hi, at the minimum, you need pretty much all of the packages in the list above. You don't need hcc and hip-hcc on systems with ROCm 3.4 and above. 

If you have installed ATMI from package repos, that's fine. No need to compile ATMI from source (unless you're using some special features) 

If your system doesn't have hsakmt-roct that leads me to think that your ROCm installation is not complete. Can you compile & run HIP examples on this system? Is it Linux? At least ATMI, and ROCr (hsa-rocr-dev and hsa-ext-rocr-dev) need hsakmt* packages and the ROCK kernel driver.

**Comment by Rombur** [comment]
Oh sorry you are right `hsakmt-roct` is installed. For some reason, it was the only library in `lib64` everything else is in `lib`.

**Comment by amberhassaan** [comment]
Glad to hear that. I'll close the issue for now.
